global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'gateway'
    static_configs:
      - targets: ['gateway:8080']
    metrics_path: /metrics

  - job_name: 'user-service'
    static_configs:
      - targets: ['user-service:8081']
    metrics_path: /metrics

  - job_name: 'tweet-service'
    static_configs:
      - targets: ['tweet-service:8082']
    metrics_path: /metrics

  - job_name: 'timeline-service'
    static_configs:
      - targets: ['timeline-service:8083']
    metrics_path: /metrics
